// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/luckDice.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderID       string                 `protobuf:"bytes,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	CustomerID    string                 `protobuf:"bytes,2,opt,name=customerID,proto3" json:"customerID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMsg) Reset() {
	*x = RequestMsg{}
	mi := &file_proto_luckDice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMsg) ProtoMessage() {}

func (x *RequestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_luckDice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMsg.ProtoReflect.Descriptor instead.
func (*RequestMsg) Descriptor() ([]byte, []int) {
	return file_proto_luckDice_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMsg) GetOrderID() string {
	if x != nil {
		return x.OrderID
	}
	return ""
}

func (x *RequestMsg) GetCustomerID() string {
	if x != nil {
		return x.CustomerID
	}
	return ""
}

type ResponseMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lucky         bool                   `protobuf:"varint,1,opt,name=lucky,proto3" json:"lucky,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMsg) Reset() {
	*x = ResponseMsg{}
	mi := &file_proto_luckDice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMsg) ProtoMessage() {}

func (x *ResponseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_luckDice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMsg.ProtoReflect.Descriptor instead.
func (*ResponseMsg) Descriptor() ([]byte, []int) {
	return file_proto_luckDice_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseMsg) GetLucky() bool {
	if x != nil {
		return x.Lucky
	}
	return false
}

var File_proto_luckDice_proto protoreflect.FileDescriptor

const file_proto_luckDice_proto_rawDesc = "" +
	"\n" +
	"\x14proto/luckDice.proto\x12\x10luckDice_service\"F\n" +
	"\n" +
	"RequestMsg\x12\x18\n" +
	"\aorderID\x18\x01 \x01(\tR\aorderID\x12\x1e\n" +
	"\n" +
	"customerID\x18\x02 \x01(\tR\n" +
	"customerID\"#\n" +
	"\vResponseMsg\x12\x14\n" +
	"\x05lucky\x18\x01 \x01(\bR\x05lucky2Z\n" +
	"\x0fluckDiceService\x12G\n" +
	"\bIndemPay\x12\x1c.luckDice_service.RequestMsg\x1a\x1d.luckDice_service.ResponseMsgB\x03Z\x01.b\x06proto3"

var (
	file_proto_luckDice_proto_rawDescOnce sync.Once
	file_proto_luckDice_proto_rawDescData []byte
)

func file_proto_luckDice_proto_rawDescGZIP() []byte {
	file_proto_luckDice_proto_rawDescOnce.Do(func() {
		file_proto_luckDice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_luckDice_proto_rawDesc), len(file_proto_luckDice_proto_rawDesc)))
	})
	return file_proto_luckDice_proto_rawDescData
}

var file_proto_luckDice_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_luckDice_proto_goTypes = []any{
	(*RequestMsg)(nil),  // 0: luckDice_service.RequestMsg
	(*ResponseMsg)(nil), // 1: luckDice_service.ResponseMsg
}
var file_proto_luckDice_proto_depIdxs = []int32{
	0, // 0: luckDice_service.luckDiceService.IndemPay:input_type -> luckDice_service.RequestMsg
	1, // 1: luckDice_service.luckDiceService.IndemPay:output_type -> luckDice_service.ResponseMsg
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_luckDice_proto_init() }
func file_proto_luckDice_proto_init() {
	if File_proto_luckDice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_luckDice_proto_rawDesc), len(file_proto_luckDice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_luckDice_proto_goTypes,
		DependencyIndexes: file_proto_luckDice_proto_depIdxs,
		MessageInfos:      file_proto_luckDice_proto_msgTypes,
	}.Build()
	File_proto_luckDice_proto = out.File
	file_proto_luckDice_proto_goTypes = nil
	file_proto_luckDice_proto_depIdxs = nil
}
