// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: proto/luckDice.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LuckDiceService_IndemPay_FullMethodName = "/luckDice_service.luckDiceService/IndemPay"
)

// LuckDiceServiceClient is the client API for LuckDiceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LuckDiceServiceClient interface {
	IndemPay(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*ResponseMsg, error)
}

type luckDiceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLuckDiceServiceClient(cc grpc.ClientConnInterface) LuckDiceServiceClient {
	return &luckDiceServiceClient{cc}
}

func (c *luckDiceServiceClient) IndemPay(ctx context.Context, in *RequestMsg, opts ...grpc.CallOption) (*ResponseMsg, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseMsg)
	err := c.cc.Invoke(ctx, LuckDiceService_IndemPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LuckDiceServiceServer is the server API for LuckDiceService service.
// All implementations must embed UnimplementedLuckDiceServiceServer
// for forward compatibility.
type LuckDiceServiceServer interface {
	IndemPay(context.Context, *RequestMsg) (*ResponseMsg, error)
	mustEmbedUnimplementedLuckDiceServiceServer()
}

// UnimplementedLuckDiceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLuckDiceServiceServer struct{}

func (UnimplementedLuckDiceServiceServer) IndemPay(context.Context, *RequestMsg) (*ResponseMsg, error) {
	return nil, status.Error(codes.Unimplemented, "method IndemPay not implemented")
}
func (UnimplementedLuckDiceServiceServer) mustEmbedUnimplementedLuckDiceServiceServer() {}
func (UnimplementedLuckDiceServiceServer) testEmbeddedByValue()                         {}

// UnsafeLuckDiceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LuckDiceServiceServer will
// result in compilation errors.
type UnsafeLuckDiceServiceServer interface {
	mustEmbedUnimplementedLuckDiceServiceServer()
}

func RegisterLuckDiceServiceServer(s grpc.ServiceRegistrar, srv LuckDiceServiceServer) {
	// If the following call panics, it indicates UnimplementedLuckDiceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LuckDiceService_ServiceDesc, srv)
}

func _LuckDiceService_IndemPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LuckDiceServiceServer).IndemPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LuckDiceService_IndemPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LuckDiceServiceServer).IndemPay(ctx, req.(*RequestMsg))
	}
	return interceptor(ctx, in, info, handler)
}

// LuckDiceService_ServiceDesc is the grpc.ServiceDesc for LuckDiceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LuckDiceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "luckDice_service.luckDiceService",
	HandlerType: (*LuckDiceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IndemPay",
			Handler:    _LuckDiceService_IndemPay_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/luckDice.proto",
}
