package main

type Order struct {
	OrderID    string // uuid, generated by us!
	CustomerID string
	ProductID  string
	Amount     int // supposely positive but not enforced

	Status       OrderStatus
	FailureType  FailureType // null-able!

	
}

type OrderStatus int

const (
	Pending OrderStatus = 0

	Succeeded OrderStatus = 1
	
	Failed  OrderStatus = -99 // 库存不足/账户没钱等
)

type FailureType string

const (
	FailedNoInvent FailureType = "FAILED_NO_INVENT"
	FailedNoLuck   FailureType = "FAILED_NO_LUCK"
)
